language: node_js
node_js: node
services:
  - mongodb
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - development
script:
  # lint, test, generate coverage
  - yarn start validate.withCoverage
  # build client code for distribution
  - yarn start client
after_success:
  # send coverage data to CodeCov
  - yarn start reportCoverage
